import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import POKEMON_LOGO from "../../public/pokeball.svg";
import Link from "next/link";
import AuthProvider from "./contexts/AuthContext";
import LoginButtonGroup from "./components/layout/LoginButtonGroup";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <div className="flex gap-4 justify-center items-center relative">
              <Link href="/">
                <Image src={POKEMON_LOGO} height={40} />
              </Link>
              <h1 className="text-center text-4xl py-5 uppercase tracking-wide">
                Pokemon Next Application
              </h1>
            </div>

            <div className="flex-grow">
              <LoginButtonGroup />
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
